---

# Update AWS Route53 DNS records
# - https://docs.ansible.com/ansible/latest/collections/community/aws/route53_module.html

- hosts: client
  vars_files: 
  - "{{ aws_secrets_file }}"
  vars: 
    ansible_python_interpreter: /usr/local/bin/python3
  tasks: 

  - name: Gather DNS records
    set_fact: 
      dns_records:
        - zone: "{{ dns_cvad_kubevirt_zone }}"
          type: A
          record: "{{ dns_cvad_kubevirt_api }}"
          ips: "{{ dns_cvad_kubevirt_ip }}"
        - zone: "{{ dns_cvad_kubevirt_zone }}"
          type: A
          record: "{{ dns_cvad_kubevirt_routes }}"
          ips: "{{ dns_cvad_kubevirt_ip }}"
        - zone: "{{ dns_cvad_mgmt_zone }}"
          type: A
          record: "{{ dns_cvad_mgmt_api }}"
          ips: "{{ dns_cvad_mgmt_ip }}"
        - zone: "{{ dns_cvad_mgmt_zone }}"
          type: A
          record: "{{ dns_cvad_mgmt_routes }}"
          ips: "{{ dns_cvad_mgmt_ip }}"

  - name: Update Route53
    with_items: "{{ dns_records }}"
    loop_control:
      loop_var: dnsrec
    community.aws.route53:
      state: present
      zone: "{{ dnsrec.zone }}"
      record: "{{ dnsrec.record }}"
      type: "{{ dnsrec.type }}"
      ttl: 7200
      value: "{{ dnsrec.ips }}"
      wait: yes



