---

# Update AWS Route53 DNS records
# - https://docs.ansible.com/ansible/latest/collections/community/aws/route53_module.html

- hosts: client
  vars_files: 
  - "{{ aws_secrets_file }}"
  tasks: 

  - name: Update Route53
    with_items: "{{ awsroute53_records }}"
    loop_control:
      loop_var: recname
    vars: 
      dnsrecord: "{{ awsroute53_records[recname] }}"
    community.aws.route53:
      state: present
      record: "{{ dnsrecord.record }}"
      value: "{{ dnsrecord.ips }}"
      zone: "{{ dnsrecord.zone }}"
      type: "{{ dnsrecord.type }}"
      ttl: 7200
      wait: yes



